Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ram-demo-bucket-2i4ryhwekljgfsblfigsjvbk
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ea3c35c5c3284d82
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-011f7dca83b7c12c9
          GroupSet:
            - sg-007a9a95e6d2a3572
